# Generated by Django 3.2.7 on 2021-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
