# Generated by Django 4.0 on 2021-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_in',
            field=models.DateTimeField(default='2021-12-14 22:17:53'),
        ),
    ]
