# Generated by Django 4.0 on 2021-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_product_added_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_in',
            field=models.DateTimeField(default='2021-12-14 22:19:35'),
        ),
    ]
