# Generated by Django 3.2.7 on 2021-12-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_product_added_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='pub files')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
