# Generated by Django 3.2.7 on 2021-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default="None", max_length=40),
            preserve_default=False,
        ),
    ]
