# Generated by Django 3.2.7 on 2021-12-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
