# Generated by Django 3.2.7 on 2021-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
